/**
 * FASE 2 ? Verificaciùn OAuth en base de datos
 * Consulta api_credentials para aliexpress-dropshipping y escribe OAUTH_DB_VERIFICATION_REPORT.md
 * Uso: npx ts-node -r tsconfig-paths/register scripts/verify-oauth-db.ts
 *      o desde backend: node --loader ts-node/esm scripts/verify-oauth-db.ts (segùn tu setup)
 */

import path from 'path';
import fs from 'fs';

const REPORT_PATH = path.resolve(__dirname, '..', '..', 'OAUTH_DB_VERIFICATION_REPORT.md');

async function main(): Promise<void> {
  const report: string[] = [
    '# OAUTH DB VERIFICATION REPORT',
    '',
    'Generated by backend/scripts/verify-oauth-db.ts',
    '',
  ];

  try {
    const { prisma } = await import('../src/config/database');
    const { decrypt } = await import('../src/utils/encryption');

    const rows = await prisma.apiCredential.findMany({
      where: { apiName: 'aliexpress-dropshipping', isActive: true },
      select: { userId: true, environment: true, credentials: true, updatedAt: true },
    });

    if (rows.length === 0) {
      report.push('OAUTH_DB_STATUS: **INVALID**');
      report.push('');
      report.push('Reason: No api_credentials found with apiName = `aliexpress-dropshipping` and isActive = true.');
      report.push('Action: Complete OAuth flow for AliExpress Dropshipping API and ensure credentials are saved.');
      fs.writeFileSync(REPORT_PATH, report.join('\n'), 'utf8');
      console.error('[VERIFY-OAUTH-DB] No aliexpress-dropshipping credentials found.');
      process.exit(1);
    }

    let anyValid = false;
    for (const row of rows) {
      let parsed: Record<string, any> = {};
      try {
        const decrypted = decrypt(row.credentials);
        parsed = JSON.parse(decrypted) || {};
      } catch (e) {
        report.push(`- userId ${row.userId} (${row.environment}): decrypt/parse error`);
        continue;
      }
      const accessToken = parsed.accessToken && String(parsed.accessToken).trim();
      const refreshToken = parsed.refreshToken != null ? String(parsed.refreshToken).trim() : '';
      const expAt = parsed.accessTokenExpiresAt ? new Date(parsed.accessTokenExpiresAt).getTime() : 0;
      const notExpired = !expAt || expAt > Date.now();

      if (accessToken && notExpired) {
        anyValid = true;
        report.push(`- userId ${row.userId} (${row.environment}): accessToken present, refreshToken ${refreshToken ? 'present' : 'optional'}, not expired`);
      } else {
        report.push(`- userId ${row.userId} (${row.environment}): ${!accessToken ? 'missing accessToken' : 'expired or missing expiry'}`);
      }
    }

    report.unshift('');
    report.unshift('OAUTH_DB_STATUS: ' + (anyValid ? '**VALID**' : '**INVALID**'));
    report.unshift('');

    if (!anyValid) {
      report.push('');
      report.push('Reason: No row with valid accessToken and non-expired token.');
      fs.writeFileSync(REPORT_PATH, report.join('\n'), 'utf8');
      console.error('[VERIFY-OAUTH-DB] No valid OAuth credentials.');
      process.exit(1);
    }

    fs.writeFileSync(REPORT_PATH, report.join('\n'), 'utf8');
    console.log('[VERIFY-OAUTH-DB] OAUTH_DB_STATUS = VALID. Report written to OAUTH_DB_VERIFICATION_REPORT.md');
  } catch (e: any) {
    report.push('OAUTH_DB_STATUS: **ERROR**');
    report.push('');
    report.push('Error: ' + (e?.message || String(e)));
    fs.writeFileSync(REPORT_PATH, report.join('\n'), 'utf8');
    console.error('[VERIFY-OAUTH-DB]', e?.message || e);
    process.exit(1);
  }
}

main();
